### ISSUE TITLE
inconsistency for comment at start of file

### ISSUE THREAD

**Issue by ze42** [PyCQA/baron#44]
Hello,

Little unconsistency when parsing comment at start of file.

If it starts with a newline, we alternate endl/comment:

```
parse('\n#foo\n#bar\n')
Out[7]: 
[{'formatting': [], 'indent': '', 'type': 'endl', 'value': '\n'},
 {'formatting': [], 'type': 'comment', 'value': '#foo'},
 {'formatting': [], 'indent': '', 'type': 'endl', 'value': '\n'},
 {'formatting': [], 'type': 'comment', 'value': '#bar'},
 {'formatting': [], 'indent': '', 'type': 'endl', 'value': '\n'}]
```

If it starts with a comment, we get a endl that includes the comment as formatting.

```
parse('#foo\n#bar\n')
[{'formatting': [{'formatting': [], 'type': 'comment', 'value': '#foo'}],
  'indent': '',
  'type': 'endl',
  'value': '\n'},
 {'formatting': [], 'type': 'comment', 'value': '#bar'},
 {'formatting': [], 'indent': '', 'type': 'endl', 'value': '\n'}]
```

Not too sure what the proper behaviour is supposed to be, but I guess it should be something similar in both cases.

**Comment by gtors** [comment]
I replace `group_generator` (from formatting_grouper.py)  with:
```python
def group_generator(sequence):
    iterator = FlexibleIterator(sequence)
    current = None, None
    while not iterator.end():
        current = next(iterator)

        if current is None:
            return

        # -------------> Remove COMMENT from here <-------------
        if current[0] in ("SPACE") and iterator.show_next() and iterator.show_next()[0] in GROUP_SPACE_BEFORE:
            new_current = next(iterator)
            current = (new_current[0], new_current[1], [current])

        if current[0] in GROUP_SPACE_AFTER + STRING and\
            # -------------------------------------------------> And here <-------
            (iterator.show_next() and iterator.show_next()[0] in ("SPACE")) and\
    #... rest part of function
```

After that `parse('#foo\n#bar\n')` works as expected:

**Comment by ibizaman** [comment]
@gtors nice catch! Thanks for figuring this out!

**Comment by bootandy** [comment]
I have just tried gtors ' change and it seems to be correct. Is there any reason this fix doesn't have a pull request? If not I will create one.

**Comment by ibizaman** [comment]
@bootandy no, just not having much time to devote to baron lately. Sorry about that. :sob:

**Comment by Psycojoker** [comment]
Me neither :/

I'll try to do a small bugfix release next weekend with this fix and https://github.com/PyCQA/redbaron/pull/118 but can't promise.

**Comment by rojaster** [comment]
I fixed it for my fork of baron :) and hey , another guy found similar bug

**Comment by ibizaman** [comment]
@bootandy Thanks for the PR @ze42 Closing as it's fix. Don't hesitate to reopen if you have any other issue.
